import { DomainDetailType } from '../interfaces/descriptor.interface';
import { DomainDescriptorDictionary, TraitDescriptorDictionary } from '../interfaces/summary.interface';
export declare const Big5Descriptor: DomainDetailType;
export declare const Big5TraitDescriptor: DomainDetailType;
export declare const Big5TraitSummary: DomainDetailType;
export declare const Big5TraitDimension: DomainDetailType;
export declare const Additional4Summary: DomainDetailType;
export declare const Additional4Descriptor: DomainDetailType;
export declare const WorkInterestLegacyDescriptor: DomainDetailType;
export declare const WorkInterestLegacySummary: DomainDetailType;
export declare const WorkInterestThrive: DomainDetailType;
export declare const WorkInterestWorkingWith: DomainDetailType;
export declare const WorkInterestWatchout: DomainDetailType;
export declare const WorkStyleLegacySummary: DomainDetailType;
export declare const WorkStyleWorkingWith: DomainDetailType;
export declare const WorkStyleThrive: DomainDetailType;
export declare const WorkStyleWatchout: DomainDetailType;
export declare const WorkValueLegacyDescriptor: DomainDetailType;
export declare const WorkValueLegacySummary: DomainDetailType;
export declare const WorkValueThrive: DomainDetailType;
export declare const WorkValueWorkingWith: DomainDetailType;
export declare const WorkValueWatchout: DomainDetailType;
export declare const DomainDescriptorDict: DomainDescriptorDictionary;
export declare const TraitDescriptorDict: TraitDescriptorDictionary;
